import express from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import adminRoutes from './routes/adminRoutes.js';
const app = express();
app.use(express.json());
app.use(cookieParser());
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5174', credentials: true }));
app.get('/api/health', (req, res) => res.json({ success: true, message: 'Admin API is up' }));
app.use('/api/admin', adminRoutes);
app.use((req, res) => res.status(404).json({ success: false, message: `Route not found: ${req.originalUrl}` }));
app.use((err, req, res, next) => { console.error(err); res.status(err.statusCode || 500).json({ success: false, message: err.message || 'Internal server error' }); });
export default app;
